output_dir: ~/scratch/siamdiff_outputs

dataset:
  class: PIPDataset
  path: 
    - ~/scratch/protein-datasets/PPI-DIPS-split/DIPS-split/data/train
    - ~/scratch/protein-datasets/PPI-DIPS-split/DIPS-split/data/val
    - ~/scratch/protein-datasets/PPI-DIPS-split/DIPS-split/data/test
  graph_construction_model:
    class: GraphConstruction
    edge_layers:
      - class: SpatialEdge
        radius: 4.5
        min_distance: 0
    edge_feature: gearnet
  atom_feature: residue_symbol
  residue_feature: null

task:
  class: PIP
  model:
    class: GearNet
    input_dim: 39
    hidden_dims: [128, 128, 128, 128, 128, 128]
    batch_norm: True
    short_cut: True
    concat_hidden: True
    readout: mean
    num_relation: 1
    edge_input_dim: 53
    num_angle_bin: 8
  num_mlp_layer: 3

optimizer:
  class: AdamW
  lr: 1.0e-4
  weight_decay: 0

engine:
  gpus: [0]
  batch_size: 8
  num_worker: 4

model_checkpoint: {{ ckpt }}

train:
  num_epoch: 10
  train_time: 120
  val_time: 20
  test_time: 10
  eval_metric: auroc [interaction]
