output_dir: ~/scratch/siamdiff_outputs

dataset:
  class: RESDataset
  path: ~/scratch/protein-datasets/
  atom_feature: null
  residue_feature: default
  transform:
    class: AtomFeature
    atom_feature: residue_symbol

task:
  class: RES
  model:
    class: GearNet
    input_dim: 39
    hidden_dims: [128, 128, 128, 128, 128, 128]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: mean
    num_relation: 1
    edge_input_dim: 53
    num_angle_bin: 8
  num_mlp_layer: 3
  graph_construction_model:
    class: GraphConstruction
    edge_layers:
      - class: SpatialEdge
        radius: 4.5
        min_distance: 0
    edge_feature: gearnet

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 64

model_checkpoint: {{ ckpt }}

eval_metric: micro_acc

train:
  num_epoch: 10
  
