output_dir: ~/scratch/siamdiff_outputs

dataset:
  class: AlphaFoldDB
  path: ~/scratch/protein-datasets/alphafold
  species_start: 0
  species_end: 21
  # species_id: 3
  # split_id: 1
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: residue
      - class: TruncateProtein
        max_length: 150
        random: True
      - class: NoiseTransform
        noise_type: gaussian
        sigma: 0.3

task:
  class: SiamDiff
  num_mlp_layer: 3
  sigma_begin: 1.0e-3
  sigma_end: 0.1
  num_noise_level: 100
  gamma: 0.5
  use_MI: True
  model:
    class: GearNet
    input_dim: 21
    hidden_dims: [ 512, 512, 512, 512, 512, 512 ]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: 'sum'
    num_relation: 7
    edge_input_dim: 59
    num_angle_bin: 8
  graph_construction_model:
    class: GraphConstruction
    node_layers:
        - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
    edge_feature: gearnet

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 16
  log_interval: 100

save_interval: 5
save_model: False

train:
  num_epoch: 25
