output_dir: ~/scratch/siamdiff_outputs

dataset:
  class: ECDataset
  path: ~/scratch/protein-datasets/
  test_cutoff: 0.95
  atom_feature: null
  residue_feature: default
  transform:
    class: ProteinView
    view: residue

task:
  class: EC
  model:
    class: GearNet
    input_dim: 21
    hidden_dims: [ 512, 512, 512, 512, 512, 512 ]
    batch_norm: True
    concat_hidden: True
    short_cut: True
    readout: 'sum'
    num_relation: 7
    edge_input_dim: 59
    num_angle_bin: 8
  num_mlp_layer: 3
  graph_construction_model:
    class: GraphConstruction
    node_layers:
        - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
    edge_feature: gearnet

optimizer:
  class: Adam
  lr: 1.0e-4

scheduler:
  class: ReduceLROnPlateau
  factor: 0.6
  patience: 5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 2
  log_interval: 1000

model_checkpoint: {{ ckpt }}

eval_metric: f1_max

train:
  num_epoch: 50
